// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_db_conn`, `get_state`, `update_novel_word_count`
// These types are ignored because they are not used by any `pub` functions: `DbState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<Novel> openProject({required String path}) =>
    RustLib.instance.api.crateApiOpenProject(path: path);

Future<void> closeProject() => RustLib.instance.api.crateApiCloseProject();

Future<List<Novel>> getNovels() => RustLib.instance.api.crateApiGetNovels();

Future<PlatformInt64> createNovel({
  required String title,
  required String genre,
  required String targetAudience,
  required PlatformInt64 targetWordCount,
}) => RustLib.instance.api.crateApiCreateNovel(
  title: title,
  genre: genre,
  targetAudience: targetAudience,
  targetWordCount: targetWordCount,
);

Future<void> updateNovel({
  required PlatformInt64 id,
  required String title,
  required String genre,
  required String targetAudience,
  required PlatformInt64 targetWordCount,
}) => RustLib.instance.api.crateApiUpdateNovel(
  id: id,
  title: title,
  genre: genre,
  targetAudience: targetAudience,
  targetWordCount: targetWordCount,
);

Future<void> deleteNovel({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiDeleteNovel(id: id);

Future<List<StepProgress>> getStepsProgress({required PlatformInt64 novelId}) =>
    RustLib.instance.api.crateApiGetStepsProgress(novelId: novelId);

Future<void> saveStepProgress({required StepProgress progress}) =>
    RustLib.instance.api.crateApiSaveStepProgress(progress: progress);

Future<List<Character>> getCharacters({required PlatformInt64 novelId}) =>
    RustLib.instance.api.crateApiGetCharacters(novelId: novelId);

Future<PlatformInt64> saveCharacter({required Character character}) =>
    RustLib.instance.api.crateApiSaveCharacter(character: character);

Future<void> deleteCharacter({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiDeleteCharacter(id: id);

Future<List<Scene>> getScenes({required PlatformInt64 novelId}) =>
    RustLib.instance.api.crateApiGetScenes(novelId: novelId);

Future<PlatformInt64> saveScene({required Scene scene}) =>
    RustLib.instance.api.crateApiSaveScene(scene: scene);

Future<void> deleteScene({
  required PlatformInt64 id,
  required PlatformInt64 novelId,
}) => RustLib.instance.api.crateApiDeleteScene(id: id, novelId: novelId);

Future<List<Chapter>> getChapters({required PlatformInt64 novelId}) =>
    RustLib.instance.api.crateApiGetChapters(novelId: novelId);

Future<PlatformInt64> saveChapter({required Chapter chapter}) =>
    RustLib.instance.api.crateApiSaveChapter(chapter: chapter);

Future<void> deleteChapter({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiDeleteChapter(id: id);

Future<String> exportToTxt({
  required List<String> titles,
  required List<String> contents,
}) => RustLib.instance.api.crateApiExportToTxt(
  titles: titles,
  contents: contents,
);

Future<void> exportToDocx({
  required String path,
  required List<String> titles,
  required List<String> contents,
}) => RustLib.instance.api.crateApiExportToDocx(
  path: path,
  titles: titles,
  contents: contents,
);

class Chapter {
  final PlatformInt64? id;
  final PlatformInt64 novelId;
  final String title;
  final String content;
  final PlatformInt64 sortOrder;

  const Chapter({
    this.id,
    required this.novelId,
    required this.title,
    required this.content,
    required this.sortOrder,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      novelId.hashCode ^
      title.hashCode ^
      content.hashCode ^
      sortOrder.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Chapter &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          novelId == other.novelId &&
          title == other.title &&
          content == other.content &&
          sortOrder == other.sortOrder;
}

class Character {
  final PlatformInt64? id;
  final PlatformInt64 novelId;
  final String name;
  final String motivation;
  final String goal;
  final String conflict;
  final String epiphany;
  final String oneParagraphSummary;
  final String fullSynopsis;

  const Character({
    this.id,
    required this.novelId,
    required this.name,
    required this.motivation,
    required this.goal,
    required this.conflict,
    required this.epiphany,
    required this.oneParagraphSummary,
    required this.fullSynopsis,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      novelId.hashCode ^
      name.hashCode ^
      motivation.hashCode ^
      goal.hashCode ^
      conflict.hashCode ^
      epiphany.hashCode ^
      oneParagraphSummary.hashCode ^
      fullSynopsis.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Character &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          novelId == other.novelId &&
          name == other.name &&
          motivation == other.motivation &&
          goal == other.goal &&
          conflict == other.conflict &&
          epiphany == other.epiphany &&
          oneParagraphSummary == other.oneParagraphSummary &&
          fullSynopsis == other.fullSynopsis;
}

class Novel {
  final PlatformInt64? id;
  final String title;
  final String genre;
  final String targetAudience;
  final PlatformInt64 targetWordCount;
  final PlatformInt64 currentWordCount;
  final String? createdAt;

  const Novel({
    this.id,
    required this.title,
    required this.genre,
    required this.targetAudience,
    required this.targetWordCount,
    required this.currentWordCount,
    this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      genre.hashCode ^
      targetAudience.hashCode ^
      targetWordCount.hashCode ^
      currentWordCount.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Novel &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          genre == other.genre &&
          targetAudience == other.targetAudience &&
          targetWordCount == other.targetWordCount &&
          currentWordCount == other.currentWordCount &&
          createdAt == other.createdAt;
}

class Scene {
  final PlatformInt64? id;
  final PlatformInt64 novelId;
  final PlatformInt64? povCharacterId;
  final String setting;
  final String plotThread;
  final String whatHappens;
  final PlatformInt64 expectedWordCount;
  final PlatformInt64 actualWordCount;

  const Scene({
    this.id,
    required this.novelId,
    this.povCharacterId,
    required this.setting,
    required this.plotThread,
    required this.whatHappens,
    required this.expectedWordCount,
    required this.actualWordCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      novelId.hashCode ^
      povCharacterId.hashCode ^
      setting.hashCode ^
      plotThread.hashCode ^
      whatHappens.hashCode ^
      expectedWordCount.hashCode ^
      actualWordCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Scene &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          novelId == other.novelId &&
          povCharacterId == other.povCharacterId &&
          setting == other.setting &&
          plotThread == other.plotThread &&
          whatHappens == other.whatHappens &&
          expectedWordCount == other.expectedWordCount &&
          actualWordCount == other.actualWordCount;
}

class StepProgress {
  final PlatformInt64? id;
  final PlatformInt64 novelId;
  final PlatformInt64 stepNumber;
  final String contentText;
  final bool isCompleted;

  const StepProgress({
    this.id,
    required this.novelId,
    required this.stepNumber,
    required this.contentText,
    required this.isCompleted,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      novelId.hashCode ^
      stepNumber.hashCode ^
      contentText.hashCode ^
      isCompleted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StepProgress &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          novelId == other.novelId &&
          stepNumber == other.stepNumber &&
          contentText == other.contentText &&
          isCompleted == other.isCompleted;
}
