// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1038853322;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_core',
        ioDirectory: '../rust_core/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiCloseProject();

  Future<PlatformInt64> crateApiCreateNovel({
    required String title,
    required String genre,
    required String targetAudience,
    required PlatformInt64 targetWordCount,
  });

  Future<void> crateApiDeleteChapter({required PlatformInt64 id});

  Future<void> crateApiDeleteCharacter({required PlatformInt64 id});

  Future<void> crateApiDeleteNovel({required PlatformInt64 id});

  Future<void> crateApiDeleteScene({
    required PlatformInt64 id,
    required PlatformInt64 novelId,
  });

  Future<void> crateApiExportToDocx({
    required String path,
    required List<String> titles,
    required List<String> contents,
  });

  Future<String> crateApiExportToTxt({
    required List<String> titles,
    required List<String> contents,
  });

  Future<List<Chapter>> crateApiGetChapters({required PlatformInt64 novelId});

  Future<List<Character>> crateApiGetCharacters({
    required PlatformInt64 novelId,
  });

  Future<List<Novel>> crateApiGetNovels();

  Future<List<Scene>> crateApiGetScenes({required PlatformInt64 novelId});

  Future<List<StepProgress>> crateApiGetStepsProgress({
    required PlatformInt64 novelId,
  });

  Future<Novel> crateApiOpenProject({required String path});

  Future<PlatformInt64> crateApiSaveChapter({required Chapter chapter});

  Future<PlatformInt64> crateApiSaveCharacter({required Character character});

  Future<PlatformInt64> crateApiSaveScene({required Scene scene});

  Future<void> crateApiSaveStepProgress({required StepProgress progress});

  Future<void> crateApiUpdateNovel({
    required PlatformInt64 id,
    required String title,
    required String genre,
    required String targetAudience,
    required PlatformInt64 targetWordCount,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiCloseProject() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCloseProjectConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCloseProjectConstMeta =>
      const TaskConstMeta(debugName: "close_project", argNames: []);

  @override
  Future<PlatformInt64> crateApiCreateNovel({
    required String title,
    required String genre,
    required String targetAudience,
    required PlatformInt64 targetWordCount,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(title, serializer);
          sse_encode_String(genre, serializer);
          sse_encode_String(targetAudience, serializer);
          sse_encode_i_64(targetWordCount, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCreateNovelConstMeta,
        argValues: [title, genre, targetAudience, targetWordCount],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCreateNovelConstMeta => const TaskConstMeta(
    debugName: "create_novel",
    argNames: ["title", "genre", "targetAudience", "targetWordCount"],
  );

  @override
  Future<void> crateApiDeleteChapter({required PlatformInt64 id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDeleteChapterConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeleteChapterConstMeta =>
      const TaskConstMeta(debugName: "delete_chapter", argNames: ["id"]);

  @override
  Future<void> crateApiDeleteCharacter({required PlatformInt64 id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDeleteCharacterConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeleteCharacterConstMeta =>
      const TaskConstMeta(debugName: "delete_character", argNames: ["id"]);

  @override
  Future<void> crateApiDeleteNovel({required PlatformInt64 id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDeleteNovelConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeleteNovelConstMeta =>
      const TaskConstMeta(debugName: "delete_novel", argNames: ["id"]);

  @override
  Future<void> crateApiDeleteScene({
    required PlatformInt64 id,
    required PlatformInt64 novelId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          sse_encode_i_64(novelId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDeleteSceneConstMeta,
        argValues: [id, novelId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeleteSceneConstMeta => const TaskConstMeta(
    debugName: "delete_scene",
    argNames: ["id", "novelId"],
  );

  @override
  Future<void> crateApiExportToDocx({
    required String path,
    required List<String> titles,
    required List<String> contents,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_list_String(titles, serializer);
          sse_encode_list_String(contents, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiExportToDocxConstMeta,
        argValues: [path, titles, contents],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExportToDocxConstMeta => const TaskConstMeta(
    debugName: "export_to_docx",
    argNames: ["path", "titles", "contents"],
  );

  @override
  Future<String> crateApiExportToTxt({
    required List<String> titles,
    required List<String> contents,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(titles, serializer);
          sse_encode_list_String(contents, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiExportToTxtConstMeta,
        argValues: [titles, contents],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExportToTxtConstMeta => const TaskConstMeta(
    debugName: "export_to_txt",
    argNames: ["titles", "contents"],
  );

  @override
  Future<List<Chapter>> crateApiGetChapters({required PlatformInt64 novelId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(novelId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_chapter,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetChaptersConstMeta,
        argValues: [novelId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetChaptersConstMeta =>
      const TaskConstMeta(debugName: "get_chapters", argNames: ["novelId"]);

  @override
  Future<List<Character>> crateApiGetCharacters({
    required PlatformInt64 novelId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(novelId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_character,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetCharactersConstMeta,
        argValues: [novelId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetCharactersConstMeta =>
      const TaskConstMeta(debugName: "get_characters", argNames: ["novelId"]);

  @override
  Future<List<Novel>> crateApiGetNovels() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_novel,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetNovelsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetNovelsConstMeta =>
      const TaskConstMeta(debugName: "get_novels", argNames: []);

  @override
  Future<List<Scene>> crateApiGetScenes({required PlatformInt64 novelId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(novelId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_scene,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetScenesConstMeta,
        argValues: [novelId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetScenesConstMeta =>
      const TaskConstMeta(debugName: "get_scenes", argNames: ["novelId"]);

  @override
  Future<List<StepProgress>> crateApiGetStepsProgress({
    required PlatformInt64 novelId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(novelId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_step_progress,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetStepsProgressConstMeta,
        argValues: [novelId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetStepsProgressConstMeta => const TaskConstMeta(
    debugName: "get_steps_progress",
    argNames: ["novelId"],
  );

  @override
  Future<Novel> crateApiOpenProject({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_novel,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiOpenProjectConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOpenProjectConstMeta =>
      const TaskConstMeta(debugName: "open_project", argNames: ["path"]);

  @override
  Future<PlatformInt64> crateApiSaveChapter({required Chapter chapter}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_chapter(chapter, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSaveChapterConstMeta,
        argValues: [chapter],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSaveChapterConstMeta =>
      const TaskConstMeta(debugName: "save_chapter", argNames: ["chapter"]);

  @override
  Future<PlatformInt64> crateApiSaveCharacter({required Character character}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_character(character, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSaveCharacterConstMeta,
        argValues: [character],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSaveCharacterConstMeta =>
      const TaskConstMeta(debugName: "save_character", argNames: ["character"]);

  @override
  Future<PlatformInt64> crateApiSaveScene({required Scene scene}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_scene(scene, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSaveSceneConstMeta,
        argValues: [scene],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSaveSceneConstMeta =>
      const TaskConstMeta(debugName: "save_scene", argNames: ["scene"]);

  @override
  Future<void> crateApiSaveStepProgress({required StepProgress progress}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_step_progress(progress, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSaveStepProgressConstMeta,
        argValues: [progress],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSaveStepProgressConstMeta => const TaskConstMeta(
    debugName: "save_step_progress",
    argNames: ["progress"],
  );

  @override
  Future<void> crateApiUpdateNovel({
    required PlatformInt64 id,
    required String title,
    required String genre,
    required String targetAudience,
    required PlatformInt64 targetWordCount,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          sse_encode_String(title, serializer);
          sse_encode_String(genre, serializer);
          sse_encode_String(targetAudience, serializer);
          sse_encode_i_64(targetWordCount, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiUpdateNovelConstMeta,
        argValues: [id, title, genre, targetAudience, targetWordCount],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUpdateNovelConstMeta => const TaskConstMeta(
    debugName: "update_novel",
    argNames: ["id", "title", "genre", "targetAudience", "targetWordCount"],
  );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Chapter dco_decode_box_autoadd_chapter(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_chapter(raw);
  }

  @protected
  Character dco_decode_box_autoadd_character(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_character(raw);
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  Scene dco_decode_box_autoadd_scene(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_scene(raw);
  }

  @protected
  StepProgress dco_decode_box_autoadd_step_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_step_progress(raw);
  }

  @protected
  Chapter dco_decode_chapter(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return Chapter(
      id: dco_decode_opt_box_autoadd_i_64(arr[0]),
      novelId: dco_decode_i_64(arr[1]),
      title: dco_decode_String(arr[2]),
      content: dco_decode_String(arr[3]),
      sortOrder: dco_decode_i_64(arr[4]),
    );
  }

  @protected
  Character dco_decode_character(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return Character(
      id: dco_decode_opt_box_autoadd_i_64(arr[0]),
      novelId: dco_decode_i_64(arr[1]),
      name: dco_decode_String(arr[2]),
      motivation: dco_decode_String(arr[3]),
      goal: dco_decode_String(arr[4]),
      conflict: dco_decode_String(arr[5]),
      epiphany: dco_decode_String(arr[6]),
      oneParagraphSummary: dco_decode_String(arr[7]),
      fullSynopsis: dco_decode_String(arr[8]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<Chapter> dco_decode_list_chapter(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_chapter).toList();
  }

  @protected
  List<Character> dco_decode_list_character(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_character).toList();
  }

  @protected
  List<Novel> dco_decode_list_novel(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_novel).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<Scene> dco_decode_list_scene(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_scene).toList();
  }

  @protected
  List<StepProgress> dco_decode_list_step_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_step_progress).toList();
  }

  @protected
  Novel dco_decode_novel(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return Novel(
      id: dco_decode_opt_box_autoadd_i_64(arr[0]),
      title: dco_decode_String(arr[1]),
      genre: dco_decode_String(arr[2]),
      targetAudience: dco_decode_String(arr[3]),
      targetWordCount: dco_decode_i_64(arr[4]),
      currentWordCount: dco_decode_i_64(arr[5]),
      createdAt: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  Scene dco_decode_scene(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return Scene(
      id: dco_decode_opt_box_autoadd_i_64(arr[0]),
      novelId: dco_decode_i_64(arr[1]),
      povCharacterId: dco_decode_opt_box_autoadd_i_64(arr[2]),
      setting: dco_decode_String(arr[3]),
      plotThread: dco_decode_String(arr[4]),
      whatHappens: dco_decode_String(arr[5]),
      expectedWordCount: dco_decode_i_64(arr[6]),
      actualWordCount: dco_decode_i_64(arr[7]),
    );
  }

  @protected
  StepProgress dco_decode_step_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return StepProgress(
      id: dco_decode_opt_box_autoadd_i_64(arr[0]),
      novelId: dco_decode_i_64(arr[1]),
      stepNumber: dco_decode_i_64(arr[2]),
      contentText: dco_decode_String(arr[3]),
      isCompleted: dco_decode_bool(arr[4]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  Chapter sse_decode_box_autoadd_chapter(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_chapter(deserializer));
  }

  @protected
  Character sse_decode_box_autoadd_character(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_character(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  Scene sse_decode_box_autoadd_scene(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_scene(deserializer));
  }

  @protected
  StepProgress sse_decode_box_autoadd_step_progress(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_step_progress(deserializer));
  }

  @protected
  Chapter sse_decode_chapter(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_novelId = sse_decode_i_64(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_sortOrder = sse_decode_i_64(deserializer);
    return Chapter(
      id: var_id,
      novelId: var_novelId,
      title: var_title,
      content: var_content,
      sortOrder: var_sortOrder,
    );
  }

  @protected
  Character sse_decode_character(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_novelId = sse_decode_i_64(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_motivation = sse_decode_String(deserializer);
    var var_goal = sse_decode_String(deserializer);
    var var_conflict = sse_decode_String(deserializer);
    var var_epiphany = sse_decode_String(deserializer);
    var var_oneParagraphSummary = sse_decode_String(deserializer);
    var var_fullSynopsis = sse_decode_String(deserializer);
    return Character(
      id: var_id,
      novelId: var_novelId,
      name: var_name,
      motivation: var_motivation,
      goal: var_goal,
      conflict: var_conflict,
      epiphany: var_epiphany,
      oneParagraphSummary: var_oneParagraphSummary,
      fullSynopsis: var_fullSynopsis,
    );
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<Chapter> sse_decode_list_chapter(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Chapter>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_chapter(deserializer));
    }
    return ans_;
  }

  @protected
  List<Character> sse_decode_list_character(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Character>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_character(deserializer));
    }
    return ans_;
  }

  @protected
  List<Novel> sse_decode_list_novel(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Novel>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_novel(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<Scene> sse_decode_list_scene(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Scene>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_scene(deserializer));
    }
    return ans_;
  }

  @protected
  List<StepProgress> sse_decode_list_step_progress(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <StepProgress>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_step_progress(deserializer));
    }
    return ans_;
  }

  @protected
  Novel sse_decode_novel(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_genre = sse_decode_String(deserializer);
    var var_targetAudience = sse_decode_String(deserializer);
    var var_targetWordCount = sse_decode_i_64(deserializer);
    var var_currentWordCount = sse_decode_i_64(deserializer);
    var var_createdAt = sse_decode_opt_String(deserializer);
    return Novel(
      id: var_id,
      title: var_title,
      genre: var_genre,
      targetAudience: var_targetAudience,
      targetWordCount: var_targetWordCount,
      currentWordCount: var_currentWordCount,
      createdAt: var_createdAt,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Scene sse_decode_scene(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_novelId = sse_decode_i_64(deserializer);
    var var_povCharacterId = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_setting = sse_decode_String(deserializer);
    var var_plotThread = sse_decode_String(deserializer);
    var var_whatHappens = sse_decode_String(deserializer);
    var var_expectedWordCount = sse_decode_i_64(deserializer);
    var var_actualWordCount = sse_decode_i_64(deserializer);
    return Scene(
      id: var_id,
      novelId: var_novelId,
      povCharacterId: var_povCharacterId,
      setting: var_setting,
      plotThread: var_plotThread,
      whatHappens: var_whatHappens,
      expectedWordCount: var_expectedWordCount,
      actualWordCount: var_actualWordCount,
    );
  }

  @protected
  StepProgress sse_decode_step_progress(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_novelId = sse_decode_i_64(deserializer);
    var var_stepNumber = sse_decode_i_64(deserializer);
    var var_contentText = sse_decode_String(deserializer);
    var var_isCompleted = sse_decode_bool(deserializer);
    return StepProgress(
      id: var_id,
      novelId: var_novelId,
      stepNumber: var_stepNumber,
      contentText: var_contentText,
      isCompleted: var_isCompleted,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_chapter(Chapter self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_chapter(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_character(
    Character self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_character(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_scene(Scene self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_scene(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_step_progress(
    StepProgress self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_step_progress(self, serializer);
  }

  @protected
  void sse_encode_chapter(Chapter self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_i_64(self.id, serializer);
    sse_encode_i_64(self.novelId, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_i_64(self.sortOrder, serializer);
  }

  @protected
  void sse_encode_character(Character self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_i_64(self.id, serializer);
    sse_encode_i_64(self.novelId, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.motivation, serializer);
    sse_encode_String(self.goal, serializer);
    sse_encode_String(self.conflict, serializer);
    sse_encode_String(self.epiphany, serializer);
    sse_encode_String(self.oneParagraphSummary, serializer);
    sse_encode_String(self.fullSynopsis, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_chapter(List<Chapter> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_chapter(item, serializer);
    }
  }

  @protected
  void sse_encode_list_character(
    List<Character> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_character(item, serializer);
    }
  }

  @protected
  void sse_encode_list_novel(List<Novel> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_novel(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_scene(List<Scene> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_scene(item, serializer);
    }
  }

  @protected
  void sse_encode_list_step_progress(
    List<StepProgress> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_step_progress(item, serializer);
    }
  }

  @protected
  void sse_encode_novel(Novel self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_i_64(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.genre, serializer);
    sse_encode_String(self.targetAudience, serializer);
    sse_encode_i_64(self.targetWordCount, serializer);
    sse_encode_i_64(self.currentWordCount, serializer);
    sse_encode_opt_String(self.createdAt, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_scene(Scene self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_i_64(self.id, serializer);
    sse_encode_i_64(self.novelId, serializer);
    sse_encode_opt_box_autoadd_i_64(self.povCharacterId, serializer);
    sse_encode_String(self.setting, serializer);
    sse_encode_String(self.plotThread, serializer);
    sse_encode_String(self.whatHappens, serializer);
    sse_encode_i_64(self.expectedWordCount, serializer);
    sse_encode_i_64(self.actualWordCount, serializer);
  }

  @protected
  void sse_encode_step_progress(StepProgress self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_i_64(self.id, serializer);
    sse_encode_i_64(self.novelId, serializer);
    sse_encode_i_64(self.stepNumber, serializer);
    sse_encode_String(self.contentText, serializer);
    sse_encode_bool(self.isCompleted, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
